### ISSUE TITLE
Open To Pull Requests?

### ISSUE THREAD

**Issue by Robert430404** [lukasolson/fitbit-radial-clock#1]
Hey man, found your watch on the fitbit store, are you interested in accepting pull requests for the project?

**Comment by lukasolson** [comment]
Somehow I missed this, and I'm sorry!

Yes, I'm definitely interested in accepting pull requests for this project. What did you have in mind?

**Comment by Robert430404** [comment]
Sweetness, just saw your reply (so no hard feelings).

Was thinking about implementing a custom color picker for the rings/other ui elements, and offering a few other settings for additional info. (things like steps and heart rate).

What are your thoughts?

**Comment by lukasolson** [comment]
Yep, that'd be awesome! What are you thinking for the custom color picker? One that lets you set custom colors?

**Comment by Robert430404** [comment]
More or less, rather than having a preset of colors for the rings as there is now, open up a dialog for hex codes with a selector more or less.

**Comment by lukasolson** [comment]
++ sounds great. Gonna close this issue out. Thanks!

**Comment by Robert430404** [comment]
Awesome, I'll get to work then. Thanks for taking the time to respond, greatly appreciate it.
